### ISSUE TITLE
Support entity classes located in other dll, not only in main exe

### ISSUE THREAD

**Issue by Aivanovac** [buehler/dotnet-operator-sdk#103]
I have a project which will consist at list 3 controllers and 3 CRD. Sometime 1 controller will watch 1 type of CRD and update the other. So i think it will a good point to move entity classes to single shared dll. I tried to use your project and it looks really cool. But generation operations doesn't work for me. Because GenerateCrds looking for a KubernetesEntityAttribute only in main assembly. 

What do you think about this ? I can implement and make PR if you advise how to solve the problem.

**Comment by buehler** [comment]
This could be an idea. Right now, only the executing assembly is considered. Maybe I need to fetch all types that contain the `[KubernetesObject]` attribute.

Problem is, this would also include all objects from the kubernetes-client library (therefore .. all possible objects).

I think we need to create a way (or maybe an attribute) to include custom kubernetes objects from other assemblies.

**Comment by buehler** [comment]
Maybe an approach like `AutoMapper` would do.
You could be able to "Add" assemblies.

`.AddFromAssembly` for example

**Comment by erin-allison** [comment]
@Aivanovac can you have a look at #108 to see if those changes will support your use case? OperatorBuilder has an additional `AddResourceAssembly` method that'll let you load resources from other DLLs.
