### ISSUE TITLE
Changing the settings via the msbuild extensions

### ISSUE THREAD

**Issue by wkit23** [buehler/dotnet-operator-sdk#106]
How do you exactly change the default location for KubeOpsConfigRoot? I added the following to the csproj
```
	<PropertyGroup>
		<KubeOpsConfigRoot>$(SolutionDir)KubeOps</KubeOpsConfigRoot>
	</PropertyGroup>
```
But unfortunately I still see it create the files at config folder.

**Comment by buehler** [comment]
As far as I know, this should actually do the trick. Does it not?
I need to investigate the matter.

**Comment by wkit23** [comment]
Unfortunately it's not. Could it be due to VS 2019 updates (using 16.8.0 atm)

**Comment by buehler** [comment]
Oh. @wkit23 now I found it: KubeOpsConfigRoot does not exist.
I create the "config root" with: https://github.com/buehler/dotnet-operator-sdk/blob/master/src/KubeOps/Build/KubeOps.props#L4

**Comment by buehler** [comment]
Mhmm. well bonkers. It does exist.
