### ISSUE TITLE
Collection properties are generated as object instead of array in JSON schema

### ISSUE THREAD

**Issue by alexmg** [buehler/dotnet-operator-sdk#152]
The CRD code generator does not cater for a wide range of enumerable types. In the generated JSON Schema these unsupported collection properties have a `type` of `object` instead of `array` which breaks validation when posting resources. It would be ideal for the following additional types to be supported:

- `List<T>`, `IList<T>` and `IReadyOnlyList<T>`
- `Collection<T>`, `ICollection<T>` and `IReadyOnlyCollection<T>`
- `HashSet<T>`, `ISet<T>` and `IReadOnlySet<T>`
- Types derived from `List<T>` and `Collection<T>`

These could all be detected by targeting `IEnumerable<T>` based interfaces on the type.

**Comment by buehler** [comment]
Nice catch! Thank you!
