### ISSUE TITLE
Incorrect max length for finalizer names...

### ISSUE THREAD

**Issue by mmccord-mdbuyline** [buehler/dotnet-operator-sdk#193]
The max length for a finalizer domain name is 63 characters. [Per the documentation](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#finalizers) the finalizer name should be a domain name followed by a slash followed by the name of the finalizer. Probably something the following implementation for IResourceFinalizer<>.Identifier would be more appropriate:

```csharp
string Identifier
        {
            get
            {
                var crd = CustomEntityDefinitionExtensions.CreateResourceDefinition<TEntity>();
                var name = $"{crd.Group}/{GetType().Name.ToLowerInvariant()}finalizer";
                return name.Length > MaxNameLength
                    ? name.Substring(0, MaxNameLength)
                    : name;
            }
        }
```

As it stands the implementation for IResourceFinalizer<>.Identifier often yields UnprocessableEntity from the finalizer manager because the domain name length is too long.

**Comment by buehler** [comment]
Oh! Thanks for the definition. Obviously I did not search very thoroughly when researching about max names.
