### ISSUE TITLE
Finalizers are not retried after exception

### ISSUE THREAD

**Issue by anekdoti** [buehler/dotnet-operator-sdk#239]
**Describe the bug**
An uncaught exception in a finalizer terminates the operator.

**To Reproduce**
Implement an operator that registers a finalizer. Throw an exception in the method FinalizeAsync of the corresponding IResourceFinalizer.

**Expected behavior**
If an event handler in the controller throws an exception, the event is retried a number of times instead of terminating the operator. I would have expected the same for finalizers. 
In general, it is advised to implement the cleanup logic in finalizers to be idempotent, to support retries (see [here](https://book.kubebuilder.io/reference/using-finalizers.html)). I.e., the cleanup logic is called again (with some back-off time) until it completes and the finalizer can be removed.

**Comment by erin-allison** [comment]
Got this reproduced on the template. All that was necessary, as described, was simply adding a `throw new Exception();` in the `FinalizeAsync` method.

https://github.com/buehler/dotnet-operator-sdk/blob/727a73321afdb3bd2ddb1653da157e58e863ff57/src/KubeOps.Templates/Templates/Operator.CSharp/Finalizer/DemoFinalizer.cs#L18-L23

And I do agree that this is an issue; resource controllers re-queue four times upon exception, and finalizers should behave the same.

**Comment by anekdoti** [comment]
There is also no requeueing in the HandleResourceFinalization of ManagedResourceController. Would it be fine to just add a similar block as in https://github.com/buehler/dotnet-operator-sdk/blob/master/src/KubeOps/Operator/Controller/ManagedResourceController%7BTEntity%7D.cs#L248 ?

**Comment by anekdoti** [comment]
By the way: why is it exactly for retries?

**Comment by erin-allison** [comment]
> There is also no requeueing in the HandleResourceFinalization of ManagedResourceController. Would it be fine to just add a similar block as in https://github.com/buehler/dotnet-operator-sdk/blob/master/src/KubeOps/Operator/Controller/ManagedResourceController%7BTEntity%7D.cs#L248 ?

That's what I'm working on, though it's giving me a bit of grief with propagating exceptions back up the stack to be properly handled.

> By the way: why is it exactly four retries?

I know it's a finite number because you don't want to just continually hammer the API server if something's broken. 4 retries means 5 attempts over a span of ~30 seconds depending on how long it takes to fail, and that would usually be enough time for a lot of transient errors to resolve themselves. That was around well before me though, so a better answer may come from Christoph

**Comment by erin-allison** [comment]
Bah, all my troubles were because Rider wasn't rebuilding my KubeOps copy that I was changing... that should solve it.

```
info: KubeOps.Operator.Finalizer.FinalizerManager[0]
      Execute finalizer "demo.kubeops.dev/demofinalizerfinalizer" on entity "DemoEntity/test".
info: TestOperator.Finalizer.DemoFinalizer[0]
      entity test called FinalizeAsync.
fail: KubeOps.Operator.Controller.ManagedResourceController[0]
      Finalize resource "DemoEntity/test" threw an error. Retry attempt 3.
      System.Exception: Blow up the finalizer
         at TestOperator.Finalizer.DemoFinalizer.FinalizeAsync(V1DemoEntity entity) in .../TestOperator/Finalizer/DemoFinalizer.cs:line 23
         at KubeOps.Operator.Finalizer.FinalizerManager`1.<>c__DisplayClass6_1.<<KubeOps-Operator-Finalizer-IFinalizerManager<TEntity>-FinalizeAsync>b__2>d.MoveNext() in .../dotnet-operator-sdk/src/KubeOps/Operator/Finalizer/FinalizerManager{TEntity}.cs:line 82
      --- End of stack trace from previous location ---
         at KubeOps.Operator.Finalizer.FinalizerManager`1.KubeOps.Operator.Finalizer.IFinalizerManager<TEntity>.FinalizeAsync(TEntity entity) in .../dotnet-operator-sdk/src/KubeOps/Operator/Finalizer/FinalizerManager{TEntity}.cs:line 73
         at KubeOps.Operator.Controller.ManagedResourceController`1.HandleResourceFinalization(QueuedEvent data) in .../dotnet-operator-sdk/src/KubeOps/Operator/Controller/ManagedResourceController{TEntity}.cs:line 299
dbug: KubeOps.Operator.Controller.ManagedResourceController[0]
      Retry attempt 3 for event "Finalizing" on resource "DemoEntity/test" with exponential backoff "00:00:08.4030000".
```

**Comment by erin-allison** [comment]
> Maybe it be a good idea to make the number of attempts configurable - but that's not urgent and just an idea.

If that would be useful to you, I'd recommend opening up an issue for it. I personally wouldn't use it, so I'm not just going to do the work out of nowhere.

That being said, it doesn't appear that a huge change would be necessary. It should be (more or less) as simple as moving `MaxRetries` onto the `OperatorSettings` class and making it not a constant.

https://github.com/buehler/dotnet-operator-sdk/blob/02bb7ecd4309cd26ec4b3cdd60b40584fd633b94/src/KubeOps/Operator/Controller/ManagedResourceController%7BTEntity%7D.cs#L20-L23

**Comment by anekdoti** [comment]
I have to admit that currently I also don't see an immediate need for it. Sometimes a well-chosen constant is better than a configuration. If it turns out to be useful, I will make an according pull request. Thank you for pointing me to the right place!

**Comment by buehler** [comment]
That is funny, I thought I do retry finalizer as well... (～￣▽￣)～
