### ISSUE TITLE
KubeOps changes default JSON serialization settings

### ISSUE THREAD

**Issue by anekdoti** [buehler/dotnet-operator-sdk#242]
**Describe the bug**
KubeOps changes default JSON serialization settings. This might influence other components that use the default JSON serialization settings. 

**To Reproduce**
Use a JSON serializer with the default serialization settings in a KubeOps operator and outside, e.g., in a unit test.

**Expected behavior**
The serialized output should be identical (or at least when disregarding line breaks and spacing).

**Additional context**
The way field names are cased by the JSON serialization settings configured by KubeOps also seems to be problematic in general. Here are some examples for field names serialized without and with the KubeOps settings:

- client_app_id -> clienT_APP_ID
- account_name -> accounT_NAME
- session_paramenters -> sessioN_PARAMETERS

In fact, this prevents us from connecting to Snowflake using the Snowflake connector as described in #241, as running the Snowflake connector in a KubeOps operator changes the casing of the fields in its requests.

**Comment by erin-allison** [comment]
@anekdoti Can you compile and test against my changes? I believe I have removed all the points where the default settings are touched.

https://github.com/erin-allison/dotnet-operator-sdk/commit/c59c7f652ddd9daa4d5d262d14fe4c55c8d83c6d

**Comment by anekdoti** [comment]
By the way: do you have any thoughts about https://github.com/buehler/dotnet-operator-sdk/issues/239 ?

**Comment by erin-allison** [comment]
I can't speak to when @buehler will merge this in. I'll have a look at that one in the meantime and see if they can both be in the next release.

**Comment by anekdoti** [comment]
Thank you very much!

**Comment by buehler** [comment]
Hey @erin-allison and @anekdoti 

I've been on holiday the past weeks, but this seems to be a nice catch!
Looking right into it
