### ISSUE TITLE
Support conversion webhooks

### ISSUE THREAD

**Issue by anekdoti** [buehler/dotnet-operator-sdk#283]
**Is your feature request related to a problem? Please describe.**
Custom resource definitions can define so-called "conversion webhooks" that transparently convert custom resources with an older version into the storage version before they are even stored in the cluster (see [here](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/)). KubeOps already supports Mutation and Validation webhooks, but no Conversion webhooks.

**Describe the solution you'd like**
Provide a IConversionWebhook interface and register its implementations as webhooks, similar to mutation and validation webhooks.

**Comment by buehler** [comment]
Hey @anekdoti 

I already though of that in #137 
But up until now, I did not have the muse to implement them :-)

**Comment by anekdoti** [comment]
Hello @buehler , I am sorry for the long delay. Are you currently planning to implement Conversion webhooks? It would be complete the support of versioned custom resource definitions.
