### ISSUE TITLE
CustomResourceDefinition validation fails for type map[string]string 

### ISSUE THREAD

**Issue by anekdoti** [buehler/dotnet-operator-sdk#377]
**Describe the bug**
Applying a custom resource definition with type map[string]string for a field to a Kubernetes v1.20 cluster yields a validation error

`The CustomResourceDefinition "{mycrd.com}" is invalid: {long path into the crd}.type: Unsupported value: "map[string]string": supported values: "array", "boolean", "integer", "number", "object", "string"`

which makes `Dictionary<string, string>`  as a data type for a custom resource unusable.

**To Reproduce**
Define entities for a custom resource definition with the data type `Dictionary<string,string>` . (Try to) apply the CRD generated by KubeOps to your Kubernetes cluster.

**Expected behavior**
Validation should succeed and the CRD should be registered in the cluster.

**Comment by anekdoti** [comment]
Would it be possible to just roll this feature back?

**Comment by buehler** [comment]
Hey @anekdoti, yes it absolutely is.

**Comment by anekdoti** [comment]
> Can you provide some information? Do you know why Kubernetes does not accept it? Because the discussion over here: #348 @hypnopotamus stated that is should be possible.

Thank you very much for rolling this feature back. Sorry for my very late reply - I lost track of the thread. As @hypnopotamus also said, I think it was just never a feature of the schema definitions - the error message was also clear about the types that are supported.
