### ISSUE TITLE
Latest release (6.4.0) does not work and will fail with default template

### ISSUE THREAD

**Issue by ewassef** [buehler/dotnet-operator-sdk#441]
**Describe the bug**

There are several issues running the latest release on an existing or new templated project

The first is the scoped services that no longer work with Hosted services. 
ie. Leader Election and LocalTunnerl. 

Without explicitly turning off leader election, the code will not run due to the following:
 `Cannot consume scoped service 'DotnetKubernetesClient.IKubernetesClient' from singleton 'Microsoft.Extensions.Hosting.IHostedService'.`

---

another issue is that IResourceCache is not required for EventQueue which is not part of the controller, however, there is no service registration for Resourcecache and the 
`services.AddScoped<typeof(ResourceCache<>>)` doesn't do it. 
The error is 

`'Unable to resolve service for type 'KubeOps.Operator.Caching.IResourceCache`1[Operator3.Entities.V1DemoEntity]' while attempting to activate 'KubeOps.Operator.Controller.EventQueue`1[Operator3.Entities.V1DemoEntity]'.'`

**To Reproduce**
create a new project, reference .net6 language version 10 and the package version 6.4.0. Hit play

**Comment by buehler** [comment]
Is this targeting the templates or the logic itself? Because there was a bug introduced in a refactoring and now fixed with #437

**Comment by erin-allison** [comment]
I am fairly sure this is the logic itself; I had changed a couple service lifetimes to make things play nice for testing and clearly there were some issues that the tests didn't catch.

One part of this was identical to #437, but the hosted service issues are separate.

**Comment by buehler** [comment]
Therefore dixed by #437 :)

**Comment by buehler** [comment]
f

**Comment by Silvenga** [comment]
Ah, I'm surprised I didn't run into this, but I'm binding `IKubernetesClient` as a singleton in our project (also using AutoFac).

I'm assuming the work around right now is to upgrade to at least [v6.4.1](https://github.com/buehler/dotnet-operator-sdk/releases/tag/v6.4.1) and change the `IKubernetesClient` registration to a singleton.

Personally, I think `IKubernetesClient` should always be a singleton, since the referenced `Kubernetes` class does PEM parsing in the ctor (IIRC), which can just tank performance.

**Comment by erin-allison** [comment]
On second thought... I have no clue why I did what I did for that... I changed IKubernetesClient to scoped in the extensions and then overrode it back to singleton in the test stuff :confused:

Well, I've got a fix for it now

**Comment by Silvenga** [comment]
> reloading the token

Whoa, I always thought the tokens never expired e.g. https://stackoverflow.com/a/62830897/2001966

But at least some flavors (if not vanilla) do rotate tokens: https://github.com/zalando/skipper/issues/1277

**Comment by Silvenga** [comment]
Actually @erin-allison, we look safe for this to be a singleton.

https://github.com/kubernetes-client/csharp/blob/7936814751dd0b6808b819c27b1c8c16691fe073/src/KubernetesClient/Authentication/TokenFileAuth.cs#L26

The change was added in v7.0.5, which this project requires >= 7.0.15.

**Comment by erin-allison** [comment]
Ah, perfect!

I had just seen [this](https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#serviceaccount-admission-controller) referencing how bound token volumes can/do have an expiration and didn't see how the C# library handled that.

**Comment by ewassef** [comment]
This looks to still be broken: 

`'Cannot resolve scoped service 'KubeOps.Operator.Controller.IEventQueue`1[******]' from root provider.'`

Please reopen

**Comment by buehler** [comment]
actually... tracked in #450
