### ISSUE TITLE
feat: Add easy mechanism for "events" (kubernetes object events)

### ISSUE THREAD

**Issue by buehler** [buehler/dotnet-operator-sdk#5]
The kubernetes sub-resource "Events" should be supported on crds

**Comment by buehler** [comment]
@ocdi I found some documentation:
https://www.pulumi.com/docs/reference/pkg/kubernetes/events/v1beta1/event/

This states that there are events and also event series.

I tested it, when I just create 4 events on an item, the result looks like:
![image](https://user-images.githubusercontent.com/1067213/97164614-b2547980-1782-11eb-93bd-e314f6f8d102.png)

But it would be cool to have a mechanism in place that looks more like the events on a deployment

**Comment by tomkerkhove** [comment]
Cool stuff!

**Comment by buehler** [comment]
Thanks @tomkerkhove!
I had an idea on how to implement it.
If you'd like, you can review the changes. Maybe you have some input on the api or the way of doing things?

As it seems I got a build problem. So it's not released yet.

**Comment by tomkerkhove** [comment]
Sure, feel free to assign if you can and I'll do it asap!

**Comment by buehler** [comment]
I'd like to, but I cant assign you to the PR.
https://github.com/buehler/dotnet-operator-sdk/pull/132
It seems that github does not allow someone to be assigned (even "only" as reviewer) if the person is not a collaborator.
