### ISSUE TITLE
Use of internal class in example tests

### ISSUE THREAD

**Issue by lucid-at-dream** [buehler/dotnet-operator-sdk#508]
https://github.com/buehler/dotnet-operator-sdk/blob/4ecf08d48e9f7867a3db613c85d228c62c56e849/tests/KubeOps.TestOperator.Test/TestController.Test.cs#L24

`IControllerInstanceBuilder` is an internal class. Since these examples are mentioned in the documentation consider creating the example in a way that someone using KubeOps as a NuGet dependency can use it.

Also, congrats for the awesome work!

**Comment by buehler** [comment]
Very good point.

**Comment by buehler** [comment]
Nice you found a workaround :-) Although this should not be the case. I try to find a way to expose a possibility to get controllers.

/cc @erin-allison

**Comment by erin-allison** [comment]
I'm of a mind to say that's purely a documentation issue. For unit testing a controller, I would construct just the controller, and not bring in all of the other framework "stuff" that wraps it during run-time.

You can resolve it by requesting the implementation type from your DI container or by building it by hand if you want to configure/load in mock dependencies.

**Comment by buehler** [comment]
Actually, that's a good statement. I did not think about that.

I currently think about the "correct" way of integration testing the whole operator while using unit tests as @erin-allison mentioned.

**Comment by lucid-at-dream** [comment]
That's a very good point @erin-allison I'll give it a shot at simplifying the setup code.

Indeed I don't think it will take much to trigger reconcile events for a given controller. I'll get back with the final solution, perhaps open a PR here if it's worth it.

**Comment by buehler** [comment]
Actually, you can trigger / enqueue events with the factory.. just start / run the factory then all controllers should run as well. When you enqueue your event, the reconcile event should trigger.
You can mock your own implementation and see if something was triggered.
