### ISSUE TITLE
web is down 

### ISSUE THREAD

**Issue by trojaj12** [buehler/dotnet-operator-sdk#510]
**Describe the bug**
[web](https://buehler.github.io/dotnet-operator-sdk/) is down.

**Screenshots**
![image](https://user-images.githubusercontent.com/43502696/214457477-a5156b44-c810-4e26-a7b8-7154ca20f074.png)

**Comment by buehler** [comment]
https://github.com/buehler/dotnet-operator-sdk/discussions/509
-> the whole documentation was moved into the respective readme files.

**Comment by buehler** [comment]
(if required, I can publishe a GH page with a redirect to the readme files.)

**Comment by trojaj12** [comment]
Ok, since there are some other website pointing to that link it might be nice to redirect users.
It up to you

**Comment by buehler** [comment]
Did not think of that. Good point.

**Comment by trojaj12** [comment]
Just an example:
The official Kubernetes website points to your site.
[https://kubernetes.io/docs/concepts/extend-kubernetes/operator/#writing-operator](https://kubernetes.io/docs/concepts/extend-kubernetes/operator/#writing-operator)

**Comment by buehler** [comment]
Oh wow... I personally added that with a PR. Now that's unlucky :D

**Comment by buehler** [comment]
https://buehler.github.io/dotnet-operator-sdk/ It's up again :-)
