### ISSUE TITLE
[bug]: disable build tasks when output is not exe

### ISSUE THREAD

**Issue by vvitkovsky** [buehler/dotnet-operator-sdk#543]
### Describe the bug

I have added KubeOps nuget package to my RecorderProxy sub project, and try to build app:

Rebuild started...
Restored C:\Sources\service-recorder-proxy\RecorderProxyServiceModels\RecorderProxyModels.csproj (in 1 ms).
Restored C:\Sources\service-recorder-proxy\EQ\EventQueueApi\EventQueueApi.csproj (in 20 ms).
Restored C:\Sources\service-recorder-proxy\EQ\EqRabbitMQ\EqRabbitMQ.csproj (in 20 ms).
Restored C:\Sources\service-recorder-proxy\RecorderProxyService.Dahua\RecorderProxy.Dahua.csproj (in 20 ms).
Restored C:\Sources\service-recorder-proxy\RecorderProxy\RecorderProxy.csproj (in 181 ms).
Restored C:\Sources\service-recorder-proxy\RecorderProxyService\RecorderProxyService.csproj (in 181 ms).
1>------ Rebuild All started: Project: EventQueueApi, Configuration: Debug Any CPU ------
2>------ Rebuild All started: Project: RecorderProxyModels, Configuration: Debug Any CPU ------
2>RecorderProxyModels -> C:\Sources\service-recorder-proxy\RecorderProxyServiceModels\bin\Debug\net7.0\RecorderProxyModels.dll
1>EventQueueApi -> C:\Sources\service-recorder-proxy\EQ\EventQueueApi\bin\Debug\net6.0\EventQueueApi.dll
3>------ Rebuild All started: Project: EqRabbitMQ, Configuration: Debug Any CPU ------
3>EqRabbitMQ -> C:\Sources\service-recorder-proxy\EQ\EqRabbitMQ\bin\Debug\net6.0\EqRabbitMQ.dll
4>------ Rebuild All started: Project: RecorderProxy.Dahua, Configuration: Debug Any CPU ------
4>RecorderProxy.Dahua -> C:\Sources\service-recorder-proxy\RecorderProxyService.Dahua\bin\Debug\net7.0\RecorderProxy.Dahua.dll
5>------ Rebuild All started: Project: RecorderProxy, Configuration: Debug Any CPU ------
5>RecorderProxy -> C:\Sources\service-recorder-proxy\RecorderProxy\bin\Debug\net7.0\RecorderProxy.dll
5>Generating Dockerfile
5>A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\Sources\service-recorder-proxy\RecorderProxy\bin\Debug\net7.0\'.
5>Failed to run as a self-contained app.
5>  - The application was run as a self-contained app because 'C:\Sources\service-recorder-proxy\RecorderProxy\bin\Debug\net7.0\RecorderProxy.runtimeconfig.json' was not found.
5>  - If this should be a framework-dependent app, add the 'C:\Sources\service-recorder-proxy\RecorderProxy\bin\Debug\net7.0\RecorderProxy.runtimeconfig.json' file and specify the appropriate framework.
5>C:\Users\victor.vitkovskiy\.nuget\packages\kubeops\7.1.1\build\KubeOps.targets(63,5): error MSB3073: The command "dotnet bin\Debug\net7.0\RecorderProxy.dll generator docker --out C:\Sources\service-recorder-proxy\RecorderProxy\Dockerfile --dotnet-tag latest --solution-dir C:\Sources\service-recorder-proxy\ --target-file RecorderProxy.dll --project-path C:\Sources\service-recorder-proxy\RecorderProxy\RecorderProxy.csproj" exited with code -2147450749.
5>Done building project "RecorderProxy.csproj" -- FAILED.
========== Rebuild All: 4 succeeded, 1 failed, 0 skipped ==========
========== Elapsed 00:01,308 ==========

It tries to find some RecorderProxy.runtimeconfig.json file that doesn't exists.

### To reproduce

Add KybeOps nuget to your subprj
Build solution

### Expected behavior

No error during build

**Comment by vvitkovsky** [comment]
It works if I will just disable all tasks in sub project file like this:
  <PropertyGroup>
    <KubeOpsSkipDockerfile>""</KubeOpsSkipDockerfile>
    <KubeOpsSkipCrds>""</KubeOpsSkipCrds>
    <KubeOpsSkipRbac>""</KubeOpsSkipRbac>
    <KubeOpsSkipOperator>""</KubeOpsSkipOperator>
    <KubeOpsSkipInstaller>""</KubeOpsSkipInstaller>
  </PropertyGroup>

**Comment by buehler** [comment]
Is it because of other repository things or because of KubeOps?

**Comment by vvitkovsky** [comment]
It is because KubeOps nuget is used in subproject assembly, not in main WebApi project, then you can't build it without modifications that I mentioned.

**Comment by erin-allison** [comment]
https://github.com/buehler/dotnet-operator-sdk/issues/73

Looks like you're building a DLL and the current generator setup doesn't like that.

**Comment by vvitkovsky** [comment]
Yes, if I build .exe all is ok. I just tried to link KubeOps to dependent dll like this:
- MyProject.exe <- KubeOps nuget (works ok)
   - MyFisrt.dll <- KubeOps nuget (doesn't work, need to disable tasks)

Is it possible to disable tasks for dll automatically somehow?
If not - then anyway there is a workaround how to do this.
