### ISSUE TITLE
[bug]: StatusModified Event must support returning ResourceControllerResult

### ISSUE THREAD

**Issue by llorente-od** [buehler/dotnet-operator-sdk#579]
### Describe the bug

Reconcile event supports returning ResourceControllerResult specifying not only the event to requeue but also a TimeSpan to schedule the next execution.

Currently Reconcile, StatusModified and Deleted are the supported events. Since StatusModified is triggered automatically on CustomResource Status changes, it just feels weird for reconcile to return ResourceControllerResult enqueuing a StatusModified event if no changes happened, and if event is gonna be triggered automatically in case something changed on the status.

Now to explain the scenario. As explained on the docs, it makes sense to requeue the reconcile under some circustances, like checking database connection. on my specific case, I've few controllers, and the two mostly impacted are a controller executing monitoring of the entire cluster and a controller implementing autoscaling features (a bit smarter than HPA basically making use of k8s CustomMetrics and some others). Both of them have quite a lot reasons to update the CustomResource Entity Status that is being reconciled, during the execution of the reconcile event, for everything to be automated and keep track of what each controller is dicovering on each execution.

However, by doing so, right after Reconcile event, StatusModified Event is triggered, which returns "Event type "StatusUpdated" on resource "Kheiron/kheiron" successfully reconciled. **Requeue not possible.**" and breaks the next execution of Reconcile event, not happening on the specific timespan that was returned, but on the default of 5 minutes. This happens regardless of playing with OperatorSettings.DefaultRequeueAsSameType or returning ResourceControllerResult.RequeueEvent(requeue, ResourceEventType.Reconcile)

From my perspective, to fix this StatusModified must be able to return null if nothing needs to be requeued or ResourceControllerResult to enqueue a new Reconcile event.

### To reproduce

1. Create a controller
2. Define ReconcileAsync & StatusModifiedAsync
3. Update Entity Status during ReconcileAsync
4. Exit ReconcileAsync returning ResourceControllerResult with a desired TimeSpan in which to requeue Reconcile event

### Expected behavior

1. ReconcileAsync executes
2. Entity Status is updated successfully
3. ReconcileAsync exits requeueing a new ReconcileEvent to me executed in the specified TimeSpan
4. StatusModified executes as Entity Status was updated
5. ReconcileAsync executes again after previous requeue TimeSpan

**Comment by Crespalvaro** [comment]
First, sorry for misleading, I accdentally published this issue with the wrong account but in fact im in charge of this issue.

I've advertised that throwing an exception from withing StatusModified method "fixes" this issue, which makes me believe this actually could be a bug related with the EventQueue, and not an actual intended behaviour.  After throwing the exception the new reconcile occurs after the intended delay.

For the time being I have no clue of how returning Task.CompletedTask, and continuing the execution normally, prevents to manage the Event that was previously registered at ReconcileAsync.

**Comment by jamescooke-vwfs** [comment]
We are facing the same issue and are struggling to find a workaround.

We even tried throwing the exception, but this makes the reconciliation process repeat immediately, not after the desired delay (but also throwing an exception isn't a valid workaround).

This happens **every time** we try and return a RequeueEvent from ReconcileAsync.

**Comment by Crespalvaro** [comment]
@jamescooke-vwfs pls take a look at #585 seems like a working solution could be reach soon

**Comment by buehler** [comment]
This has drastically changed in V8.
