### ISSUE TITLE
Preload the resource cache on watcher start

### ISSUE THREAD

**Issue by buehler** [buehler/dotnet-operator-sdk#58]
Currently, the watcher is started up and all elements that are found in the namespaces are fired with a "created" event. This may be problematic for certain operators.

A better way would be to fetch a list of already existing objects in kubernetes with the client and preload the cache with the existing objects. So when the watcher starts, all elements that prematurely existed in kubernetes would fire a "not modified" event.

**Comment by buehler** [comment]
Actually, this could also be problematic with CRD instances created while the operator was down.
So this mechanism has to be as it is.

**Comment by sabbadino** [comment]
I understand your point, still this behaviour could be an option that can be specified at startup, in some scenario it might be what one needs

**Comment by buehler** [comment]
Actually, this is a good point. If this is configurable, people can decide whether they want to use it or not.

**Comment by erin-allison** [comment]
This will be interesting to implement. When querying Kubernetes for a watch (even if you hit the API directly) it looks to return an "added" event for all preexisting resources.

Kubectl handles this with its "--watch-only" flag, which gets the initial list to find the current highest ResourceVersion, then starts the watch beginning at that version, skipping printing of the initial list of objects. It looks like this is another argument which could get added into `IKubernetesClient.Watch<TResource>` in https://github.com/buehler/dotnet-kubernetes-client

This could be controlled by an option in `OperatorSettings`, determining whether to use the default (current) behavior or this new methodology.

**Comment by sabbadino** [comment]
Sounds good 👍
