### ISSUE TITLE
[bug]: `webhooks install` command does not entirely replace existing webhooks when `-r` is specified

### ISSUE THREAD

**Issue by ian-buse** [buehler/dotnet-operator-sdk#587]
### Describe the bug

I initially implemented my IValidationWebhook interface with the following line, along with its corresponding `Create` method:

```c#
public AdmissionOperations => AdmissionOperations.Create;
```

After later adding an `Update` webhook, I changed the line to this:

```c#
public AdmissionOperations => AdmissionOperations.Create | AdmissionOperations.Update;
```

However, after running `dotnet run -- webhooks install -r` to replace the existing webhook configuration, the webhook definition for the operator webhook still had the following operation rules:

```json
"rules": [
    {
        "operations": [
            "CREATE"
        ],
    }
],
```

I wasn't able to get this section to update using the `webhooks install -r` command, and had to manually delete the webhook configuration in Kubernetes (`kubectl delete validatingwebhookconfiguration validators.testoperator`) before running the command again.

### To reproduce

1. Implement a "Create" method for the IValdiationWebhook interface.
2. Set the `Operations` field to `AdmissionOperations.Create`
3. Install the webhooks.
4. Implement an "Update" method for the IValidationWebhook interface.
5. Set the `Operations` field to `AdmissionOperations.Create | AdmissionOperations.Update`
6. Try installing the webhooks again using the `-r` option in the command to "replace already existing webhooks"
7. Run the operator, apply a CRD, and then update the CRD and see that it does not try to use the webhook on update

### Expected behavior

The webhook is replaced in its entirety, including the rules.

**Comment by buehler** [comment]
This is new in V8 and will not work the same way it did in v7
