### ISSUE TITLE
[feature]: Test with NativeAOT

### ISSUE THREAD

**Issue by stevefan1999-personal** [buehler/dotnet-operator-sdk#590]
### Is your feature request related to a problem? Please describe.

As .NET 8 is coming soon, we need to consider making sure NativeAOT would work out of the box. This means directly competing with Quarkus and its native image generation.

https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/?tabs=net7%2Cwindows

### Describe the solution you would like

Reduce the use of System.Reflection as much as possible

**Comment by buehler** [comment]
Hey @stevefan1999-personal 

Thank you for the suggestion. However, as far as I can recall the setup and intended usage of the framework: This will not be possible for a long time. Everything is based on reading types with special annotations and class structures to create the registrations for the types.

It may be possible with code generators but this will be a pretty big change.

**Comment by buehler** [comment]
Hey @stevefan1999-personal
I had a look into this matter while figuring out the new setup for KubeOps, however, `k8s` relies heavily on reflection.

As long as that package uses reflection, I don't know if it's possible to use nativeAOT. We'll see when .NET 8 lands.
