### ISSUE TITLE
[feature]: Middleware support

### ISSUE THREAD

**Issue by dbones** [buehler/dotnet-operator-sdk#630]
### Is your feature request related to a problem? Please describe.

I would like a mechanism to apply cross cutting concerns, similar to AspNet Middleware, Masstransit Middleware etc

### Describe the solution you would like

something like a middleware pipeline, where we can add logic pre and post the controller events

**Comment by buehler** [comment]
hey @dbones 
with v8, this could be done with simple abstraction of controllers right?
