### ISSUE TITLE
[bug]: KubeOps.Generator requires at least .NET SDK 7.0.402

### ISSUE THREAD

**Issue by PSanetra** [buehler/dotnet-operator-sdk#633]
### Describe the bug

KubeOps.Generator requires `Microsoft.CodeAnalysis.CSharp` in version `4.7.0`. This implies having the currently latest .NET SDK version `7.0.402` installed.

### To reproduce

1. Install dotnet version `7.0.111` exclusively
2. Create a KubeOps project with version `8.0.0-pre.21` which is also using the `KubeOps.Generator` package
3. Execute `dotnet build`
4. `dotnet build` fails

```
MSBuild version 17.4.8+6918b863a for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
CSC : warning CS9057: The analyzer assembly '/[...]/.nuget/packages/kubeops.generator/8.0.0-pre.21/analyzers/dotnet/cs/KubeOps.Generator.dll' references version '4.7.0.0' of the compiler, which is newer than the currently running version '4.4.0.0'. [/[...]/Example.csproj]
/[...]/Program.cs(10,14): error CS1061: 'IOperatorBuilder' does not contain a definition for 'RegisterComponents' and no accessible extension method 'RegisterComponents' accepting a first argument of type 'IOperatorBuilder' could be found (are you missing a using directive or an assembly reference?) [/[...]/Example.csproj]

Build FAILED.
```

The warning suggests that the analyzer assembly can not be used by `KubeOps.Generator` and the following build error seems to be caused by the missing execution of the `KubeOps.Generator` analyzer/generator.

### Expected behavior

* `dotnet build` should work with older .NET SDK versions than 7.0.402.

**Comment by buehler** [comment]
Hmm... this is weird.
Is there a specific reason not to upgrade?

But anyway, do you have any suggestion how I can use newest possible versions?

**Comment by buehler** [comment]
Would something like this work:
`<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="*" PrivateAssets="all" />`

**Comment by PSanetra** [comment]
My personal reason at the moment is just that the [Arch Linux package](https://archlinux.org/packages/extra/x86_64/dotnet-sdk/) is still just providing `7.0.111`. I would need to install `7.0.402` manually.

Not 100% sure, but I guess you can specify version ranges instead of specific versions on the `PackageReference Version` attribute.

Also see https://learn.microsoft.com/en-us/nuget/concepts/package-versioning#references-in-project-files-packagereference

E.g.
```xml
<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="[4.0.0,)" PrivateAssets="all" />
<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="[3.0.0,)" PrivateAssets="all" />
```
(Not sure which version is really your minium required version, but I guess you can just try and change if there are other bug reports.)
