### ISSUE TITLE
[bug]: ControllerRegistrations.g.cs issues in Rider

### ISSUE THREAD

**Issue by PSanetra** [buehler/dotnet-operator-sdk#635]
### Describe the bug

I am using Rider to develop the operator. A nice feature of Rider is the ability to inspect the generated source files in the IDE.

For some reason the `ControllerRegistrations.g.cs` is generated once after opening the IDE, but after changing anything in a Controller source file (e.g. just adding a comment somewhere), the generated file disappears from the IDE. I am not sure if there is a way to inspect generator logs in Rider.

Another strange bug, which might be related, is happening when I edit any other unrelated source code file (e.g. the `Program.cs`). In this case the `ControllerRegistrations.g.cs` seems to be regenerated, but each time I edit something, the a redundant `builder.AddController<...>();` line is added for the same `Controller` class. Maybe there is some cached state, which should be cleared before each source generation?

(By looking at the `EntityControllerSyntaxReceiver` class for some reason the List might not get cleared on regenerating the source code file.)

https://github.com/buehler/dotnet-operator-sdk/blob/93031b2894f0cfc337317fd81f44a0327a818cf9/src/KubeOps.Generator/SyntaxReceiver/EntityControllerSyntaxReceiver.cs#L8

After restarting the IDE both issues are fixed temporarily.

Not sure if the cause for these bugs could have other side effects in other circumstances.

### To reproduce

1. Create a KubeOps version `8.0.0-pre.21` project with `KubeOps.Operator` and `KubeOps.Generator` packages
2. Add a controller and an Entity to the project
3. Open the project in Rider
4. Inspect the generated source files (Project -> Dependencies -> .NET 7.0 -> Source Generators)
5. `ControllerRegistrations.g.cs` should be generated
6. Edit the controller class by e.g. adding a comment
7. `ControllerRegistrations.g.cs` disappears

### Expected behavior

`ControllerRegistrations.g.cs` should not disappear

### Screenshots

Screenshot with generated `ControllerRegistrations.g.cs`:
![screenshot_with_controllerregistrationgenerator](https://github.com/buehler/dotnet-operator-sdk/assets/7327745/237fec45-847e-4d05-8212-0224cc9d3274)

Screenshot with missing `ControllerRegistrations.g.cs`:
![screenshot_without_controllerregistrationgenerator](https://github.com/buehler/dotnet-operator-sdk/assets/7327745/765206b3-bb74-4653-8147-c8a93f692a53)

**Comment by PSanetra** [comment]
I have found an exception in Rider, when the source file disappears from Rider. This might be helpful :slightly_smiling_face: 

```
Generator 'ControllerRegistrationGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'ArgumentException' with message 'SyntaxTree is not part of the compilation (Parameter 'syntaxTree')'  System.ArgumentException: SyntaxTree is not part of the compilation (Parameter 'syntaxTree') at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetSemanticModel(SyntaxTree syntaxTree, Boolean ignoreAccessibility) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\CSharp\Portable\Compilation\CSharpCompilation.cs:line 2415 at KubeOps.Generator.Generators.ControllerRegistrationGenerator.c__DisplayClass3_0. b__2(ValueTuple`2 e) at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext() at System.Linq.Enumerable.AppendPrependIterator`1.LoadFromEnumerator() at System.Linq.Enumerable.AppendPrepend1Iterator`1.MoveNext() at Microsoft.CodeAnalysis.SyntaxList`1.CreateNode(IEnumerable`1 nodes) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\Core\Portable\Syntax\SyntaxList`1.cs:line 63 at KubeOps.Generator.Generators.ControllerRegistrationGenerator.Execute(GeneratorExecutionContext context) at Microsoft.CodeAnalysis.SourceGeneratorAdaptor. b__5_5(SourceProductionContext productionContext, GeneratorContextBuilder contextBuilder) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\Core\Portable\SourceGeneration\GeneratorAdaptor.cs:line 58 at Microsoft.CodeAnalysis.UserFunctionExtensions.c__DisplayClass3_0`2. b__0(TInput1 input1, TInput2 input2, CancellationToken token) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\Core\Portable\SourceGeneration\UserFunction.cs:line 105
```

**Comment by buehler** [comment]
I encountered the same issues. However, this seems to be a bug in Rider, not in the SDK. As soon as you use the normal "dotnet build" command, it is not an issue. This is also tested and the generated code from the generator matches the expected code in the tests.

As far as I know/think, this is an issue with Rider.
FWIW: I use rider as well :)
