### ISSUE TITLE
[bug]: Deletion events seem to be missing after ResourceWatcher reconnect

### ISSUE THREAD

**Issue by PSanetra** [buehler/dotnet-operator-sdk#675]
### Describe the bug

We ran into a hard to debug bug. It seems like our operator ran into an inconsistent state as some deletion events were not observered.

I took a look at the ResourceWatcher class. As far as I can see the watcher just resubscribes, but is not able to detect deletion while the watcher was disconnected.

### To reproduce

I guess the following is a way to reproduce the issue, but I still need to write a test like this:

1. Start an operator which connects to a [toxiproxy](https://github.com/Shopify/toxiproxy) instead of directly to Kubernetes API
2. Create a resource
3. Observe `ReconcileAsync` event
4. Configure reset_peer toxic on toxiproxy
5. Watcher should disconnect
6. Delete resource
7. Disable reset_peer toxic on toxiproxy
8. Watcher should reconnect, but `DeletedAsync` will not get called

### Expected behavior

I expect the watcher to resubscribe using the `resourceVersion` of the last observed event so that it is able to observe deletions which occured while the watcher was disconnected. See the section in the [Kubernetes documentation](https://kubernetes.io/docs/reference/using-api/api-concepts/#efficient-detection-of-changes):

> If a client watch is disconnected then that client can start a new watch from the last returned resourceVersion

Also the following condition must be considered:

> A given Kubernetes server will only preserve a historical record of changes for a limited time. Clusters using etcd 3 preserve changes in the last 5 minutes by default. When the requested watch operations fail because the historical version of that resource is not available, clients must handle the case by recognizing the status code `410 Gone`

I am not sure how I would expect the `ResourceWatcher` to handle such a `410 Gone` status code. I think in our case we will just restart our operator process, but other implementations might want to do something different. Therefore I would propose a Callback like `OnWatchFailedAndWasReset` on the `IEntityController` interface. This way the `IEntityController` implementation can choose how to handle this condition.

### Additional Context

Version: 8.0.0-pre.29

**Comment by buehler** [comment]
This is a good catch! Thank you for digging into it. Do you think "just" using the resource version of the received watched event would suffice? According to the docs it should right?

**Comment by PSanetra** [comment]
@buehler Yeah, I think that should be enough, but there needs to be a way to handle the `410 Gone` situation in which it is for the API server not possible anymore to continue from the provided resource version. I am not 100% sure how existing operator frameworks handle this situation.

**Comment by PSanetra** [comment]
@buehler fyi: I just saw accidentially that microsoft currently seems to implement the `ResourceInformer` for their Yarp Reverse Proxy. They are using the ResourceVersion, too:

https://github.com/microsoft/reverse-proxy/blob/8de40324a4d96e30f3adb55a501bd1ab1179848b/src/Kubernetes.Controller/Client/ResourceInformer.cs#L291

Maybe it is even possible to just copy that implementation as long as the Yarp MIT license is considered.

**Comment by buehler** [comment]
Hey @PSanetra,
I could use toxiproxy to simulate the matter.

```

warn: KubeOps.Operator.Watcher.ResourceWatcher[0]
      There were 6 errors / retries in the watcher. Wait 32.825s before next attempt to connect.
dbug: KubeOps.Operator.Watcher.ResourceWatcher[0]
      The watcher was closed.
dbug: KubeOps.Operator.Watcher.ResourceWatcher[0]
      Create watcher for entity of type "Operator.Entities.V1TestEntity".
trce: KubeOps.Operator.Watcher.ResourceWatcher[0]
      Received watch event "Deleted" for "TestEntity/my-test-entity", last observed resource version: 249374.
info: Operator.Controller.V1TestEntityController[0]
      Deleting entity Test Entity (my-test-entity): my-username (foobar@test.ch).

```

It did work now with the resource ID.

**Comment by PSanetra** [comment]
@buehler Alright looks good so far. But as far as I see, there is still handling of the `410 Gone` status code and the `Error` WatchEventType missing. This could lead to missing Deleted events, too.

**Comment by buehler** [comment]
As far as I can tell, there is no possibility to actually get this event. When the history is deleted by the API, you have no chance to get these events.

**Comment by PSanetra** [comment]
@buehler I think you need to cache the "seen" resources and on reconnect you need to compare which resources are missing

**Comment by buehler** [comment]
Hmm... I had such a logic once (v7...). It was a mess, not reliable and broke everytime when they changed something in the API structure. I think I'll "pause" this issue until we have some reliable data / way to actually do something about those lost events.

With the usage of these resource version strings, we get the events of the last five minutes (at least).

However, even if I cache the resources somehow, if the controller restarts, we have no chance to get the deleted resources and stuff. So to _guarantee_ that the controller does something when a resource is deleted: use a finalizer; this ensures that a resource is only deleted after all finalizers are removed.
