### ISSUE TITLE
[bug]: AdditionalPrinterColumn did not account for general type and format translation

### ISSUE THREAD

**Issue by stevefan1999-personal** [buehler/dotnet-operator-sdk#680]
### Describe the bug

If you tried to decorate an int field with AdditionalPrinterColumn, you would probably see this
```
An error occurred whiled executing Command: install
The given type System.Int32 is not a valid Kubernetes entity.
```

### To reproduce

```cs
[KubernetesEntity(Group = "webhook.dev", ApiVersion = "v1", Kind = "TestEntity")]
public partial class V1TestEntity : CustomKubernetesEntity<V1TestEntity.EntitySpec, V1TestEntity.EntityStatus>
{
    public override string ToString() => $"Test Entity ({Metadata.Name}): {Spec.Username}";

    public record EntitySpec
    {
        public string Username { get; set; } = string.Empty;
    }

    public record EntityStatus
    {
        [AdditionalPrinterColumn]
        public string Username { get; set; } = string.Empty;
        [AdditionalPrinterColumn]
        public int Count { get; set; } = 0;
    }

}
```

### Expected behavior

To have a valid formatting according to this:

> Type
> A column's type field can be any of the following (compare [OpenAPI v3 data types](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#dataTypes)):
> 
> integer – non-floating-point numbers
> number – floating point numbers
> string – strings
> boolean – true or false
> date – rendered differentially as time since this timestamp.
> If the value inside a CustomResource does not match the type specified for the column, the value is omitted. Use CustomResource validation to ensure that the value types are correct.
> 
> Format
> A column's format field can be any of the following:
> 
> int32
> int64
> float
> double
> byte
> date
> date-time
> password
> The column's format controls the style used when kubectl prints the value

https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#type

### Additional Context

Workaround:
```cs
[KubernetesEntity(Group = "webhook.dev", ApiVersion = "v1", Kind = "TestEntity")]
public partial class V1TestEntity : CustomKubernetesEntity<V1TestEntity.EntitySpec, V1TestEntity.EntityStatus>
{
    public override string ToString() => $"Test Entity ({Metadata.Name}): {Spec.Username}";

    public record EntitySpec
    {
        public string Username { get; set; } = string.Empty;
    }

    public record EntityStatus
    {
        [AdditionalPrinterColumn]
        public string Username { get; set; } = string.Empty;

        public int Count { get; set; } = 0;

        [AdditionalPrinterColumn]
        public string CountStr => $"{Count}";
    }

}
```

**Comment by buehler** [comment]
This is related to #687.
