### ISSUE TITLE
[bug]: Events are not correctly generated in relation with the source entity

### ISSUE THREAD

**Issue by oionut** [buehler/dotnet-operator-sdk#681]
### Describe the bug

The wrong event instance is updated

### To reproduce

1. Create a CR (CR1) and publish an event ``` await eventPublisher(entity, "RECONCILED", "Entity was reconciled.");```
2. Delete the CR
3. Create a new CR (CR2) and and publish an event with the same message as  ``` await eventPublisher(entity, "RECONCILED", "Entity was reconciled.");```

When running the kubectl describe CR1 no event is listed

Note: run the same scenario without step 2, the event published for the CR2 entity is visible only on CR1

### Expected behavior

When running the kubectl describe CR1, one event should be listed

### Additional Context

Potential fix: in https://github.com/buehler/dotnet-operator-sdk/blob/9bc1efaa94355103e33dc0ceded1a0b666b69629/src/KubeOps.Operator/Builder/OperatorBuilder.cs#L131, include in the event name the entity UID in order to link the name to the specific entity the event is generated for.

**Comment by oionut** [comment]
anther option would be to provide an overload that allows setting the event name from outside

**Comment by buehler** [comment]
Hey @oionut 

I think you are right with your suggestion to add the entity uid (instead of name).
