### ISSUE TITLE
Let the docs specify that the output type should be 'Exe'.

### ISSUE THREAD

**Issue by TeunKooijman** [buehler/dotnet-operator-sdk#73]
While it may seem obvious, the docs (at least as far as I can tell) do not currently mention that the output type of the generated .NET Core application should be set to Console Application (as opposed to Class Library). This will cause error messages on build such as:

`The command "dotnet path/to/dll generator crds --out path/to/config/crds --format Yaml" exited with code -2147450749`
or
`The command "dotnet path/to/dll generator docker --out path/to/Dockerfile --dotnet-tag latest --solution-dir path/to/sln  --target-file DllName.dll --project-path path/to/csproj" exited with code -2147450749.`

Just leaving this here, as it took me about twenty minutes figuring out why stuff wasn't building, even though I had followed the Getting Started section of the docs.

The fix is, ofcourse, to simply add `<OutputType>Exe</OutputType>` to your `.csproj.`.

Other than that, thanks a lot for the SDK!

**Comment by buehler** [comment]
Whoops 🙈 
This is a good point!

I guess the starting point of a custom operator should be an asp.net web application. This sets the output type automatically.
I think I need to document both.
