### ISSUE TITLE
Build hangs on generate CRD task  (kubeops 2.2.0, dotnetcore 3.1)

### ISSUE THREAD

**Issue by sabbadino** [buehler/dotnet-operator-sdk#74]
any suggestion about what i should check ?
I actually just dont need these steps in the project I am working on .. is there a way to skip them ? 
thank you 

 Task "CallTarget"
1>    Target GenerateCrds:
1>      Task "Message"
1>        Generating CRDs
1>      Done executing task "Message".
1>      Task "Message"
1>        Configuration path: E:\_sabba-dev\WareHouse\warehouseapi\config\crds
1>      Done executing task "Message".
1>      Using "Exec" task from assembly "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
1>      Task "Exec"
1>        **dotnet bin\Debug\netcoreapp3.1\warehouseapi.dll generator crds --out E:\_sabba-dev\WareHouse\warehouseapi\config\crds --format Yaml**

**Comment by buehler** [comment]
Yes there is a way to skip them: 
https://buehler.github.io/dotnet-operator-sdk/docs/ms_build.html#prop-settings
You can set properties in your csproj file to skip certain parts of the generation.

**Comment by buehler** [comment]
There aren't any logs right? Don't know what problems there could be...

**Comment by sabbadino** [comment]
What I sent you is the console output. I don't know where I should look for
additional logs..
I will try to replicate the situation in debug mode in visual studio

**Comment by buehler** [comment]
Ah alright. If you still need to disable it, the link above will guide you.
