### ISSUE TITLE
[bug]: KubeOps.CLI Tool does not contain the relevant documented functionality

### ISSUE THREAD

**Issue by marchermans** [buehler/dotnet-operator-sdk#740]
### Describe the bug

After installing KubeOps.CLI on DotNet 8.0.0 the described commands mentioned here: https://buehler.github.io/dotnet-operator-sdk/src/KubeOps.Cli/README.html do not exist.

### Example running `dotnet kubeops version`:
<details><summary>Details</summary>
<p>

```shell
marc@LBPF3X80WF:/mnt/c/Users/marc.hermans/RiderProjects/lb/Clusters/Lb.Clusters.Operator$ dotnet kubeops version
'version' was not matched. Did you mean one of the following?
--version
Required command was not provided.
Unrecognized command or argument 'version'.

Description:
  CLI for KubeOps. Commandline tool to help with management tasks such as generating or installing CRDs.

Usage:
  KubeOps.Cli [command] [options]

Options:
  --version       Show version information
  -?, -h, --help  Show help and usage information

Commands:
  g, gen, generate                Generates elements related to an operator.
  api-version, av                 Prints the actual server version of the connected kubernetes cluster.
  i, install <sln/csproj file>    Install CRDs into the cluster of the actually selected context. [default: /mnt/c/Users/marc.hermans/RiderProjects/lb/Clusters/Lb.Clusters.Operator/Lb.Clusters.Operator.csproj]
  u, uninstall <sln/csproj file>  Uninstall CRDs from the cluster of the actually selected context. [default: /mnt/c/Users/marc.hermans/RiderProjects/lb/Clusters/Lb.Clusters.Operator/Lb.Clusters.Operator.csproj]
``` 

</p>
</details> 

### Example of missing generator targets:
<details><summary>Details</summary>
<p>

```shell
marc@LBPF3X80WF:/mnt/c/Users/marc.hermans/RiderProjects/lb/Clusters/Lb.Clusters.Operator$ dotnet kubeops generate
Description:
  Generates elements related to an operator.

Usage:
  KubeOps.Cli generate [command] [options]

Options:
  -?, -h, --help  Show help and usage information

Commands:
  op, operator <name> <sln/csproj file>  Generates all required resources and configs for the operator to be built and run. [default:
                                         /mnt/c/Users/marc.hermans/RiderProjects/lb/Clusters/Lb.Clusters.Operator/Lb.Clusters.Operator.csproj]
``` 

</p>
</details> 

### Contents of tool manifest
<details><summary>Details</summary>
<p>

```json
{
  "version": 1,
  "isRoot": true,
  "tools": {
    "kubeops.cli": {
      "version": "9.0.0",
      "commands": [
        "kubeops"
      ]
    }
  }
}
``` 

</p>
</details> 
I also tried it by installing the tool globally, but no success.

### Dotnet information
<details><summary>Details</summary>
<p>

```shell
marc@LBPF3X80WF:/mnt/c/Users/marc.hermans/RiderProjects/lb/Clusters/Lb.Clusters.Operator$ dotnet --version
8.0.203
``` 

</p>
</details> 

### To reproduce

1. Create a new C# project on Dotnet 8
2. Install KubeOps libraries version 8.0.1 or higher
3. Create a controller and a webhook
4. Install KubeOps.CLI tool
5. Attempt to generate relevant .yaml files using the tool.
6. Notice the missing commands.

### Expected behavior

All documented commands to be available

**Comment by marchermans** [comment]
I was being stupid. 
I was running one side in WSL and the other in windows which confused it.

**Comment by ian-buse** [comment]
Nice, how did you end up solving this? I ran into the same issue and I didn't see any documentation on how to fix it. 

@buehler Perhaps you might be able to shed some light on how the CLI determines what commands are visible? I have a minikube cluster in a Hyper-V VM and my operator running on a Windows workstation, but I'm unable to use any commands besides install/uninstall and 'generator operator'.
