### ISSUE TITLE
[bug]: For adding Xunit for operators, on adding reference of the operator project shows amibiguous between methods or properties

### ISSUE THREAD

**Issue by aptandon** [buehler/dotnet-operator-sdk#747]
### Describe the bug

I have an operator project in C# which comprises of  controller and entity
For it to have Xunit for in order to test, when I add reference of the operator project it shows this compilation error
Severity	Code	Description	Project	File	Line	Suppression State	Details

**Error 1**
Error	CS0121	The call is ambiguous between the following methods or properties: 'ControllerRegistrations.RegisterControllers(KubeOps.Abstractions.Builder.IOperatorBuilder)' and 'ControllerRegistrations.RegisterControllers(KubeOps.Abstractions.Builder.IOperatorBuilder)'	MediaConnectTest	C:\Users\abc550\source\repos\grp-cti-oad-mediaconnect-operator\MediaConnectTest\KubeOps.Generator\KubeOps.Generator.Generators.OperatorBuilderGenerator\OperatorBuilder.g.cs	7	Active	

**Error 2:**

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	CS0121	The call is ambiguous between the following methods or properties: 'FinalizerRegistrations.RegisterFinalizers(KubeOps.Abstractions.Builder.IOperatorBuilder)' and 'FinalizerRegistrations.RegisterFinalizers(KubeOps.Abstractions.Builder.IOperatorBuilder)'	MediaConnectTest	C:\Users\ato960\source\repos\grp-cti-oad-mediaconnect-operator\MediaConnectTest\KubeOps.Generator\KubeOps.Generator.Generators.OperatorBuilderGenerator\OperatorBuilder.g.cs	8	Active	

### To reproduce

1) Create a operator project with the entities and controller
2) Now create another project inside same solution for Xunit
3) now add ref. of operator project

You will see these errors

### Expected behavior

It should not show this errror

### Screenshots

![image](https://github.com/buehler/dotnet-operator-sdk/assets/146760039/b7c38587-7801-4b03-a8f5-f2c6f072c568)

**Comment by buehler** [comment]
Hey @aptandon 

This sounds like a dependency problem, not an issue with the operator itself. You may have some broken references.

**Comment by buehler** [comment]
I'm sorry, but I think this is not an issue with KubeOps.
You should clean up the dependencies and fix nuget locally. It works with my test cases and the test code in this repository as well as the code of the other contributors.
