### ISSUE TITLE
feat: allow forcing of event method for delayed resource

### ISSUE THREAD

**Issue by sabbadino** [buehler/dotnet-operator-sdk#77]
If I re-enqueue an object in the Updated event (returning a non null TimeSpan), "My" expectation is to receive the re-enqueued object in the original callback (Updated method) when the timespan expires.
Currently the object is re-pushed in the NotModified  method

**Comment by buehler** [comment]
mhmm this is kind of the desired result (by now).
The idea behind it is, you can reschedule an object to be reconsidered after a time period. if it has not changed, then the notmodified event takes place. the idea behind it was to have a mechanism to check for db connections for example.

Maybe, the return type should be a tuple to give the possibility to set a specific method?
WDYT?

**Comment by sabbadino** [comment]
I agree with your proposal, still the default should be to call the
original method IMHO.
Enrico

**Comment by buehler** [comment]
Hmm I need to think about a propper solution, since changing the default would be a breaking change.

**Comment by buehler** [comment]
This can be a new feature, to add the possibility to force a resource event method when using a delay.
