### ISSUE TITLE
Config generated during build is put in current working directory

### ISSUE THREAD

**Issue by basilfx** [buehler/dotnet-operator-sdk#97]
I have a solution in a root folder, with an operator project in `src/operator-project/`.

If I run `dotnet build` on a solution in the root folder, then the config folder is generated in `config/`. If I run `dotnet build` in `src/operator-project/`, then the config folder is generated in `src/operator-project/config`. 

Given that generated config files are generated at build-time, and belong to the `src/operator-project/`, I would not expect them in the root folder (or actually, the current working directory), no matter how you compile it.

**Comment by buehler** [comment]
mhmm this is a good point.
